spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://iiht-capstone.cfsymgk8gtrx.us-east-1.rds.amazonaws.com:3306/capstone-test?createDatabaseIfNotExist=true"
    username: admin
    password: Abhishek123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

#  data:
#    mongodb:
#      uri: mongodb+srv://abhiTech:Umeshsonu29@abhitechchatboat.grlg4pf.mongodb.net/?retryWrites=true&w=majority&appName=AbhiTechChatBoat
#      database: "e-movies"


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082


info:
  app:
    name: "gatewayserver"
    description: "Property Gateway Server Application"
    version: "1.0.0"

userService:
  application:
    message: "Welcome the the user Service!! You can perform the basic sanity on this application like Searching, finding location of movies"

